### ISSUE TITLE
Was unable to observe node locally

### ISSUE THREAD

**Issue by vladimir-vg** [ruanpienaar/crell#1]
Hey!

This project looks interesting. I'm very curious about tracing tools for Erlang.

Tried to setup crell locally but for some reason was unable to add node. Websocket simply closes after sending `{"module":"crell_server","function":"add_node","args":["vision@vg-desktop","mycookie1"]}`.

Digged into source a bit, and noticed that `hawk:node_exists(Node)` in `crell_server:add_node` returns `{error,no_such_node}`.

Thought that this tool can only observe only nodes with hawk. Added hawk as a dependency for the app, ensured that it started. Still got same result.

What I should do to make it work? Is there an easy was to discover crell's features?

**Comment by ruanpienaar** [comment]
I've not been working this project in a while, and i've most likely broken something in my refactoring
I will fix it now , and advise what was wrong.

And suggestions and PR's are welcome :)

**Comment by ruanpienaar** [comment]
Thanks for bringing this up

**Comment by ruanpienaar** [comment]
Fixed it with [this](https://github.com/ruanpienaar/crell/commit/d99433dc73fd12a59e4cef877200252dfcf61efb) commit.

**Comment by vladimir-vg** [comment]
Thanks! It works now.

I've been working on somewhat similar for a long time (but with stored events and visual map with timeline). Just wanted explore similar apps, maybe learn some ideas. Thanks again.

**Comment by ruanpienaar** [comment]
Share me a link if possible

**Comment by vladimir-vg** [comment]
I plan to publish code in next three weeks.

For now there only old published version: https://github.com/vladimir-vg/batiscaph
Also there is a video for other demo, attempt to visualize shell: https://www.youtube.com/watch?v=6eqlLps6Flg
